import lighthouse from "@lighthouse-web3/sdk";
import { useAccount, useSignMessage } from "wagmi";

interface Conditions {
  id: number;
  chain: "hyperspace" | "filecoin";
  method: "balanceOf" | "balanceOfBatch" | "getBlockNumber";
  standardContractType: "ERC1155";
  contractAddress: string;
  returnValueTest: {
    comparator: ">=" | "<=" | "==" | ">";
    value: number;
  };
  parameters?: string[];
}

const progressCallback = (progressData: {
  total: number;
  uploaded: number;
}) => {
  let percentageDone = 100 - progressData.total / progressData?.uploaded;
  console.log(percentageDone);
};

export const useLighthouse = () => {
  const { address } = useAccount();
  const { signMessageAsync } = useSignMessage();

  const signature = async () => {
    if (!address) throw new Error("No address found.");

    const messageRequested = (await lighthouse.getAuthMessage(address)).data
      .message;
    const signedMessage = await signMessageAsync({
      message: messageRequested,
    });
    return {
      signedMessage: signedMessage,
      publicKey: address,
    };
  };

  const shareFile = async (addresses: string[]) => {
    const cid = "QmTTa7rm2nMjz6wCj9pvRsadrCKyDXm5Vmd2YyBubCvGPi";

    // Then get auth message and sign
    // Note: message should be signed by owner of file.
    const { publicKey, signedMessage } = await signature();

    const res = await lighthouse.shareFile(
      publicKey,
      addresses,
      cid,
      signedMessage
    );

    console.log(res);
    /*
      data: {
        cid: "QmTTa7rm2nMjz6wCj9pvRsadrCKyDXm5Vmd2YyBubCvGPi",
        shareTo: "0x201Bcc3217E5AA8e803B41d1F5B6695fFEbD5CeD"
      }
    */
    /*Visit: 
        https://files.lighthouse.storage/viewFile/<cid>  
      To view encrypted file
    */
  };

  /* Deploy file along with encryption */
  const encryptFile = async (
    e: React.ChangeEvent<HTMLInputElement> | string | Blob
  ) => {
    /*
       uploadEncrypted(e, publicKey, accessToken, uploadProgressCallback)
       - e: js event
       - publicKey: wallets public key
       - accessToken: your api key
       - signedMessage: message signed by the owner of publicKey
       - uploadProgressCallback: function to get progress (optional)
    */
    console.log("encryptFile", e);

    const sig = await signature();
    const response = await lighthouse.uploadEncrypted(
      // @ts-ignore
      e,
      sig.publicKey,
      import.meta.env.VITE_VERCEL_LIGHTHOUSE_API_KEY ?? "",
      sig.signedMessage,
      progressCallback
    );

    console.log(response);

    return response.data.Hash;
  };

  /* Decrypt file */
  const decryptFile = async (cid: string) => {
    // Fetch file encryption key
    const { publicKey, signedMessage } = await signature();
    console.log(signedMessage);

    const keyObject = await lighthouse.fetchEncryptionKey(
      cid,
      publicKey,
      signedMessage
    );

    // Decrypt file
    const decrypted = await lighthouse.decryptFile(cid, keyObject.data.key);
    console.log("Decrypted File", decrypted);

    // View File
    const url = URL.createObjectURL(decrypted);
    console.log(url);
    return url;
  };

  const applyAccessConditions = async (
    cid: string,
    conditions: Conditions[]
  ) => {
    // CID on which you are applying encryption
    // CID is generated by uploading a file with encryption
    // Only the owner of the file can apply access conditions

    // Aggregator is what kind of operation to apply to access conditions
    // Suppose there are two conditions then you can apply ([1] and [2]), ([1] or [2]), !([1] and [2]).
    const aggregator = "([1])";
    const { publicKey, signedMessage } = await signature();

    const response = await lighthouse.accessCondition(
      publicKey,
      cid,
      signedMessage,
      conditions,
      aggregator
    );

    console.log(response);
  };

  return {
    shareFile,
    decryptFile,
    encryptFile,
    applyAccessConditions,
  };
};
