// Autogenerated using mud system-types
import { InitSystem } from "./ethers-contracts/InitSystem";
import { MoveSystem } from "./ethers-contracts/MoveSystem";
 
export type SystemTypes = {
  "system.Init": InitSystem;
  "system.Move": MoveSystem;
};
