// Autogenerated using mud system-types
export const systemToId = {
  ActionSystem: "system.Action",
  CommitSystem: "system.Commit",
  InitSystem: "system.Init",
  MoveCharacterSystem: "system.MoveCharacterSystem",
  MoveSystem: "system.Move",
};

export const idToSystem = {
  "system.Action": "ActionSystem",
  "system.Commit": "CommitSystem",
  "system.Init": "InitSystem",
  "system.MoveCharacterSystem": "MoveCharacterSystem",
  "system.Move": "MoveSystem",
};
  