// Autogenerated using mud system-types
import ActionSystem from "../abi/ActionSystem.json";
import CommitSystem from "../abi/CommitSystem.json";
import InitSystem from "../abi/InitSystem.json";
import MoveCharacterSystem from "../abi/MoveCharacterSystem.json";
import MoveSystem from "../abi/MoveSystem.json";

export const SystemAbis = {
  "system.Action": ActionSystem.abi,
  "system.Commit": CommitSystem.abi,
  "system.Init": InitSystem.abi,
  "system.Init": MoveCharacterSystem.abi,
  "system.Move": MoveSystem.abi,
};
