// Autogenerated using mud system-types
import { ActionSystem } from "./ethers-contracts/ActionSystem";
import { CommitSystem } from "./ethers-contracts/CommitSystem";
import { InitSystem } from "./ethers-contracts/InitSystem";
import { MoveSystem } from "./ethers-contracts/MoveSystem";
 
export type SystemTypes = {
  "system.Action": ActionSystem;
  "system.Commit": CommitSystem;
  "system.Init": InitSystem;
  "system.Move": MoveSystem;
};
