// Autogenerated using mud system-types
import InitSystem from "../abi/InitSystem.json";
import MoveSystem from "../abi/MoveSystem.json";

export const SystemAbis = {
  "system.Init": InitSystem.abi,
  "system.Move": MoveSystem.abi,
};
